In [1]:
import pandas as pd
newpd = pd.DataFrame(columns=['Id', 'Target'])
trainlabels = pd.read_csv('./data/train.csv')
trainlabels.head()

/home/loong/anaconda3/envs/py3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/loong/anaconda3/envs/py3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


Id   Target
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18

In [2]:
label_names = {
    0:  "Nucleoplasm",  
    1:  "Nuclear membrane",   
    2:  "Nucleoli",   
    3:  "Nucleoli fibrillar center",   
    4:  "Nuclear speckles",
    5:  "Nuclear bodies",   
    6:  "Endoplasmic reticulum",   
    7:  "Golgi apparatus",   
    8:  "Peroxisomes",   
    9:  "Endosomes",   
    10:  "Lysosomes",   
    11:  "Intermediate filaments",   
    12:  "Actin filaments",   
    13:  "Focal adhesion sites",   
    14:  "Microtubules",   
    15:  "Microtubule ends",   
    16:  "Cytokinetic bridge",   
    17:  "Mitotic spindle",   
    18:  "Microtubule organizing center",   
    19:  "Centrosome",   
    20:  "Lipid droplets",   
    21:  "Plasma membrane",   
    22:  "Cell junctions",   
    23:  "Mitochondria",   
    24:  "Aggresome",   
    25:  "Cytosol",   
    26:  "Cytoplasmic bodies",   
    27:  "Rods & rings"
}

reverse_train_labels = dict((v,k) for k,v in label_names.items())

def fill_targets(row):
    row.Target = np.array(row.Target.split(" ")).astype(np.int)
    for num in row.Target:
        name = label_names[int(num)]
        row.loc[name] = 1
    return row
for key in label_names.keys():
    trainlabels[label_names[key]] = 0
import numpy as np
newtrainlabels = trainlabels.apply(fill_targets, axis=1)
newtrainlabels.head()

Id        Target  Nucleoplasm  \
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0       [16, 0]            1   
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [7, 1, 2, 0]            1   
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0           [5]            0   
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0           [1]            0   
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0          [18]            0   

   Nuclear membrane  Nucleoli  Nucleoli fibrillar center  Nuclear speckles  \
0                 0         0                          0                 0   
1                 1         1                          0                 0   
2                 0         0                          0                 0   
3                 1         0                          0                 0   
4                 0         0                          0                 0   

   Nuclear bodies  Endoplasmic reticulum  Golgi apparatus      ...       \
0               0                      0                0      ...        
1               0                      0                1      ...        
2               1                      0                0      ...        
3               0                      0                0      ...        
4               0                      0                0      ...        

   Microtubule organizing center  Centrosome  Lipid droplets  Plasma membrane  \
0                              0           0               0                0   
1                              0           0               0                0   
2                              0           0               0                0   
3                              0           0               0                0   
4                              1           0               0                0   

   Cell junctions  Mitochondria  Aggresome  Cytosol  Cytoplasmic bodies  \
0               0             0          0        0                   0   
1               0             0          0        0                   0   
2               0             0          0        0                   0   
3               0             0          0        0                   0   
4               0             0          0        0                   0   

   Rods & rings  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 30 columns]

In [3]:
newtrainlabels.ix[:, 2:]

/home/loong/anaconda3/envs/py3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Nucleoplasm  Nuclear membrane  Nucleoli  Nucleoli fibrillar center  \
0                1                 0         0                          0   
1                1                 1         1                          0   
2                0                 0         0                          0   
3                0                 1         0                          0   
4                0                 0         0                          0   
5                1                 0         0                          0   
6                0                 0         1                          0   
7                1                 0         0                          0   
8                1                 0         1                          0   
9                0                 0         0                          0   
10               0                 0         0                          0   
11               0                 0         0                          0   
12               1                 0         0                          0   
13               0                 0         0                          0   
14               0                 0         1                          0   
15               0                 0         0                          0   
16               1                 0         0                          0   
17               0                 0         0                          0   
18               1                 0         0                          0   
19               0                 0         0                          0   
20               1                 1         1                          0   
21               0                 0         0                          0   
22               0                 0         1                          0   
23               1                 0         0                          0   
24               0                 0         0                          1   
25               0                 0         0                          0   
26               0                 0         1                          0   
27               0                 0         0                          0   
28               0                 0         0                          0   
29               1                 0         0                          0   
...            ...               ...       ...                        ...   
31042            1                 0         0                          0   
31043            1                 0         1                          0   
31044            1                 0         0                          0   
31045            1                 0         0                          0   
31046            1                 0         0                          0   
31047            1                 0         0                          0   
31048            0                 0         0                          0   
31049            1                 0         0                          1   
31050            0                 0         0                          0   
31051            1                 0         1                          0   
31052            0                 0         0                          0   
31053            1                 0         0                          0   
31054            0                 0         0                          0   
31055            1                 0         0                          0   
31056            1                 0         0                          1   
31057            0                 0         0                          0   
31058            0                 0         0                          0   
31059            1                 0         0                          0   
31060            0                 0         0                          0   
31061            1                 0         0                          0   
310

In [10]:
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
SEED = 1234
train_test_split = MultilabelStratifiedKFold(n_splits=5, random_state=SEED)
kfold_index = train_test_split.split(trainlabels.Id, newtrainlabels.iloc[:, 2:])
for i, (df_train_index, df_test_index) in enumerate(kfold_index):
    print(df_train_index)
    print(df_test_index)

[    0     1     3 ... 31069 31070 31071]
[    2     4    15 ... 31061 31066 31068]
[    1     2     3 ... 31069 31070 31071]
[    0     6     8 ... 31054 31056 31062]
[    0     1     2 ... 31066 31068 31070]
[    5     7    18 ... 31067 31069 31071]
[    0     2     4 ... 31068 31069 31071]
[    1     3    10 ... 31059 31060 31070]
[    0     1     2 ... 31069 31070 31071]
[    9    14    24 ... 31050 31053 31065]


In [14]:
print(df_train_index.shape, df_test_index.shape)

(24859,) (6213,)


In [18]:
df_train = trainlabels.iloc[df_train_index]
df_train.head()

Id   Target  Nucleoplasm  \
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0            0   
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0            0   
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5            0   
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1            0   
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18            0   

   Nuclear membrane  Nucleoli  Nucleoli fibrillar center  Nuclear speckles  \
0                 0         0                          0                 0   
1                 0         0                          0                 0   
2                 0         0                          0                 0   
3                 0         0                          0                 0   
4                 0         0                          0                 0   

   Nuclear bodies  Endoplasmic reticulum  Golgi apparatus      ...       \
0               0                      0                0      ...        
1               0                      0                0      ...        
2               0                      0                0      ...        
3               0                      0                0      ...        
4               0                      0                0      ...        

   Microtubule organizing center  Centrosome  Lipid droplets  Plasma membrane  \
0                              0           0               0                0   
1                              0           0               0                0   
2                              0           0               0                0   
3                              0           0               0                0   
4                              0           0               0                0   

   Cell junctions  Mitochondria  Aggresome  Cytosol  Cytoplasmic bodies  \
0               0             0          0        0                   0   
1               0             0          0        0                   0   
2               0             0          0        0                   0   
3               0             0          0        0                   0   
4               0             0          0        0                   0   

   Rods & rings  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 30 columns]

In [19]:
df_test = trainlabels.iloc[df_test_index]
df_test.head()

Id  Target  Nucleoplasm  \
9   002daad6-bbc9-11e8-b2bc-ac1f6b6435d0       7            0   
14  00357b1e-bba9-11e8-b2ba-ac1f6b6435d0     6 2            0   
24  004b47de-bbca-11e8-b2bc-ac1f6b6435d0    25 3            0   
30  00508c34-bbb7-11e8-b2ba-ac1f6b6435d0     3 0            0   
32  00520f22-bb9a-11e8-b2b9-ac1f6b6435d0  14 2 0            0   

    Nuclear membrane  Nucleoli  Nucleoli fibrillar center  Nuclear speckles  \
9                  0         0                          0                 0   
14                 0         0                          0                 0   
24                 0         0                          0                 0   
30                 0         0                          0                 0   
32                 0         0                          0                 0   

    Nuclear bodies  Endoplasmic reticulum  Golgi apparatus      ...       \
9                0                      0                0      ...        
14               0                      0                0      ...        
24               0                      0                0      ...        
30               0                      0                0      ...        
32               0                      0                0      ...        

    Microtubule organizing center  Centrosome  Lipid droplets  \
9                               0           0               0   
14                              0           0               0   
24                              0           0               0   
30                              0           0               0   
32                              0           0               0   

    Plasma membrane  Cell junctions  Mitochondria  Aggresome  Cytosol  \
9                 0               0             0          0        0   
14                0               0             0          0        0   
24                0               0             0          0        0   
30                0               0             0          0        0   
32                0               0             0          0        0   

    Cytoplasmic bodies  Rods & rings  
9                    0             0  
14                   0             0  
24                   0             0  
30                   0             0  
32                   0             0  

[5 rows x 30 columns]